"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Search, Plus, Trash2, X, MoreHorizontal, ArrowDown01, CalendarIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Project } from "@/types/tactical-board";
import BoardPreview from "./BoardPreview";
import { deleteBoardAction, createBoardAction } from "@/app/(dashboard)/board/actions";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

export default function BoardsDashboard({ initialProjects = [] }: { initialProjects: Project[] }) {
  const router = useRouter();
  const [projects, setProjects] = useState<Project[]>(initialProjects);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    if (initialProjects) setProjects(initialProjects);
  }, [initialProjects]);

  // const handleCreateNew = async () => {
  //   // Navigate to new editor directly, where a new random ID is handled in the frontend, OR create one via server action
  //   // According to specs, the standard empty project will be created in UI
  //   router.push("/board/new");
  // };
  ``
  const handleCreateNew = async () => {
    try {
      // 1. Tell the backend to create the empty board
      const newBoard = await createBoardAction({
        id: "",
        name: "Untitled Board",
        fieldType: "full",
        fieldRotation: 0,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        homeTeam: {
          name: "Home Team",
          primaryColor: "#ef4444", // Red
          secondaryColor: "#ffffff",
          textColor: "#ffffff",
        },
        awayTeam: {
          name: "Away Team",
          primaryColor: "#3b82f6", // Blue
          secondaryColor: "#ffffff",
          textColor: "#ffffff",
        },
        scenes: [
          {
            // id: crypto.randomUUID(),
            id: "",
            name: "Scene 1",
            players: [],
            balls: [],
            drawings: [],
            arrows: [],
            timestamp: Date.now(),
          },
        ],
      });

      const newId = newBoard?.data?._id || newBoard?.data?.id || newBoard?._id || newBoard?.id;
      console.log(newId);

      // 2. Redirect the user to the ID generated by the backend
      // if (newBoard && newBoard.id) {
      //   router.push(`/board/${newBoard.id}`);
      // }
      if (newId) {
        router.push(`/board/${newId}`);
      } else {
        console.error("Backend did not return an ID:", newBoard);
      }
    } catch (error) {
      console.error("Error creating board:", error);
      // Add user feedback here (e.g., a toast or alert)
    }
  };

  const handleDelete = async (id: string) => {
    try {
      setProjects((prev) => prev.filter((p) => p.id !== id && (p as any)._id !== id));
      await deleteBoardAction(id);
      router.refresh();
    } catch (e) {
      console.error(e);
    }
  };

  const filteredProjects = projects.filter((p) =>
    p.name?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-background">
      <main className="max-w-7xl mx-auto px-6 pt-10 pb-6">
        <div className="mb-4 flex items-center justify-between">
          <div className="flex flex-col gap-3">
            <h1 className="text-2xl md:text-3xl font-bold tracking-tight">Tactical Boards</h1>
            <p className="text-muted-foreground">
              {projects.length} {projects.length === 1 ? "board" : "boards"}
            </p>
          </div>
          <div className="hidden md:flex items-center gap-2">
            <Button onClick={handleCreateNew} size="sm">
              <Plus className="size-4 mr-2" />
              New Board
            </Button>
          </div>
        </div>

        <div className="mb-12 flex items-center justify-between gap-4">
          <div className="flex-1 max-w-72">
            <Input
              placeholder="Search boards..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
        </div>

        {projects.length === 0 ? (
          <div className="flex flex-col items-center justify-center p-12 text-center rounded-xl border border-dashed text-muted-foreground mt-8 h-64">
            <p className="text-lg">No tactical boards yet.</p>
            <Button variant="outline" className="mt-4" onClick={handleCreateNew}>Create your first board</Button>
          </div>
        ) : filteredProjects.length === 0 ? (
          <div className="text-center p-12 text-muted-foreground">No matches found for "{searchQuery}"</div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {filteredProjects.map((project) => (
              <BoardCard
                key={(project as any)._id || project.id}
                project={project}
                onDelete={handleDelete}
              />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

function BoardCard({ project, onDelete }: { project: Project; onDelete: (id: string) => void }) {
  const router = useRouter();
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);

  const identifier = (project as any)._id || project.id;
  const createdAt = new Date(project.createdAt || Date.now()).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });

  const handleClick = (e: React.MouseEvent) => {
    e.preventDefault();
    router.push(`/board/${identifier}`);
  };

  return (
    <>
      <div onClick={handleClick} className="block h-full cursor-pointer outline-none rounded-xl group relative overflow-hidden flex flex-col transition-all duration-300 border border-border/50 bg-card hover:border-border hover:shadow-lg">
        {/* Preview Image / SVG */}
        <div className="w-full h-40 bg-muted border-b border-border/50 overflow-hidden flex items-center justify-center">
          <BoardPreview project={project} />
        </div>

        <CardContent className="flex flex-col flex-1 p-4 gap-2">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-foreground/90 line-clamp-1 truncate pr-2">{project.name || "Untitled Board"}</h3>

            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground opacity-0 group-hover:opacity-100 transition-opacity" onClick={(e) => e.stopPropagation()}>
                  <MoreHorizontal className="size-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={(e) => { e.stopPropagation(); router.push(`/board/${identifier}`); }}>
                  Open Editor
                </DropdownMenuItem>
                <DropdownMenuItem className="text-destructive focus:bg-destructive/10 focus:text-destructive" onClick={(e) => { e.stopPropagation(); setIsDeleteDialogOpen(true); }}>
                  Delete Board
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <CalendarIcon className="size-3" />
            <span>{createdAt}</span>
          </div>
        </CardContent>
      </div>

      <AlertDialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Board?</AlertDialogTitle>
            <AlertDialogDescription>Are you sure you want to permanently delete "{project.name}"?</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={() => onDelete(identifier)} className="bg-destructive hover:bg-destructive/90 text-white border-none">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
