import type { ThemeEditorState, ThemePreset, ThemeStyles } from "../types/editor";

export const COMMON_STYLES = [
  "font-sans",
  "font-serif",
  "font-mono",
  "radius",
  "shadow-opacity",
  "shadow-blur",
  "shadow-spread",
  "shadow-offset-x",
  "shadow-offset-y",
  "letter-spacing",
  "spacing",
];

export const DEFAULT_FONT_SANS =
  "Inter, system-ui, sans-serif";

export const DEFAULT_FONT_SERIF = "Georgia, serif";

export const DEFAULT_FONT_MONO = "JetBrains Mono, monospace";

const STACK_SANS =
  "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'";

const STACK_SERIF =
  'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif';

const STACK_MONO =
  'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace';

const phosphorLight: ThemeStyles = {
  background: "#fbfcf8",
  foreground: "#0f172a",
  card: "#ffffff",
  "card-foreground": "#0f172a",
  popover: "#ffffff",
  "popover-foreground": "#0f172a",
  primary: "#aff33e",
  "primary-foreground": "#000000",
  secondary: "#334155",
  "secondary-foreground": "#f8fafc",
  muted: "#f1f5f9",
  "muted-foreground": "#64748b",
  accent: "#f0fdf4",
  "accent-foreground": "#166534",
  destructive: "#ef4444",
  "destructive-foreground": "#ffffff",
  border: "#e2e8f0",
  input: "#e2e8f0",
  ring: "#aff33e",
  "chart-1": "#aff33e",
  "chart-2": "#334155",
  "chart-3": "#22c55e",
  "chart-4": "#64748b",
  "chart-5": "#94a3b8",
  sidebar: "#ffffff",
  "sidebar-foreground": "#0f172a",
  "sidebar-primary": "#aff33e",
  "sidebar-primary-foreground": "#000000",
  "sidebar-accent": "#f8fafc",
  "sidebar-accent-foreground": "#0f172a",
  "sidebar-border": "#f1f5f9",
  "sidebar-ring": "#aff33e",
  "font-sans": DEFAULT_FONT_SANS,
  "font-serif": DEFAULT_FONT_SERIF,
  "font-mono": DEFAULT_FONT_MONO,
  "shadow-color": "#000000",
  "shadow-opacity": "0.05",
  "shadow-blur": "20px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0px",
  "shadow-offset-y": "8px",
  "letter-spacing": "-0.01em",
  spacing: "0.25rem",
  radius: "0.625rem",
};

const phosphorDark: ThemeStyles = {
  ...phosphorLight,
  background: "#020617",
  foreground: "#f8fafc",
  card: "#0f172a",
  "card-foreground": "#f8fafc",
  popover: "#0f172a",
  "popover-foreground": "#f8fafc",
  primary: "#aff33e",
  "primary-foreground": "#000000",
  secondary: "#1e293b",
  "secondary-foreground": "#f8fafc",
  muted: "#1e293b",
  "muted-foreground": "#94a3b8",
  accent: "#14532d",
  "accent-foreground": "#aff33e",
  destructive: "#991b1b",
  "destructive-foreground": "#ffffff",
  border: "#1e293b",
  input: "#1e293b",
  ring: "#aff33e",
  "chart-1": "#aff33e",
  "chart-2": "#3b82f6",
  "chart-3": "#22c55e",
  "chart-4": "#a855f7",
  "chart-5": "#f59e0b",
  sidebar: "#0f172a",
  "sidebar-foreground": "#f8fafc",
  "sidebar-primary": "#aff33e",
  "sidebar-primary-foreground": "#000000",
  "sidebar-accent": "#14532d",
  "sidebar-accent-foreground": "#f8fafc",
  "sidebar-border": "#1e293b",
  "sidebar-ring": "#aff33e",
  "shadow-color": "#000000",
  "shadow-opacity": "0.4",
  "shadow-blur": "25px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0px",
  "shadow-offset-y": "10px",
};

const simpleLight: ThemeStyles = {
  background: "#ffffff",
  foreground: "#0a0a0a",
  card: "#ffffff",
  "card-foreground": "#0a0a0a",
  popover: "#ffffff",
  "popover-foreground": "#0a0a0a",
  primary: "#171717",
  "primary-foreground": "#fafafa",
  secondary: "#f5f5f5",
  "secondary-foreground": "#171717",
  muted: "#f5f5f5",
  "muted-foreground": "#737373",
  accent: "#f5f5f5",
  "accent-foreground": "#171717",
  destructive: "#e7000b",
  "destructive-foreground": "#ffffff",
  border: "#e5e5e5",
  input: "#e5e5e5",
  ring: "#a1a1a1",
  "chart-1": "#91c5ff",
  "chart-2": "#3a81f6",
  "chart-3": "#2563ef",
  "chart-4": "#1a4eda",
  "chart-5": "#1f3fad",
  sidebar: "#fafafa",
  "sidebar-foreground": "#0a0a0a",
  "sidebar-primary": "#171717",
  "sidebar-primary-foreground": "#fafafa",
  "sidebar-accent": "#f5f5f5",
  "sidebar-accent-foreground": "#171717",
  "sidebar-border": "#e5e5e5",
  "sidebar-ring": "#a1a1a1",
  "font-sans": STACK_SANS,
  "font-serif": STACK_SERIF,
  "font-mono": STACK_MONO,
  "shadow-color": "oklch(0 0 0)",
  "shadow-opacity": "0.1",
  "shadow-blur": "3px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0",
  "shadow-offset-y": "1px",
  "letter-spacing": "0em",
  spacing: "0.25rem",
  radius: "0.625rem",
};

const simpleDark: ThemeStyles = {
  ...simpleLight,
  background: "#0a0a0a",
  foreground: "#fafafa",
  card: "#171717",
  "card-foreground": "#fafafa",
  popover: "#262626",
  "popover-foreground": "#fafafa",
  primary: "#e5e5e5",
  "primary-foreground": "#171717",
  secondary: "#262626",
  "secondary-foreground": "#fafafa",
  muted: "#262626",
  "muted-foreground": "#a1a1a1",
  accent: "#404040",
  "accent-foreground": "#fafafa",
  destructive: "#ff6467",
  "destructive-foreground": "#fafafa",
  border: "#282828",
  input: "#343434",
  ring: "#737373",
  sidebar: "#171717",
  "sidebar-foreground": "#fafafa",
  "sidebar-primary": "#1447e6",
  "sidebar-accent": "#262626",
  "sidebar-accent-foreground": "#fafafa",
  "sidebar-border": "#282828",
  "sidebar-ring": "#525252",
};

const oceanLight: ThemeStyles = {
  background: "#f0f9ff",
  foreground: "#0c4a6e",
  card: "#ffffff",
  "card-foreground": "#0c4a6e",
  popover: "#ffffff",
  "popover-foreground": "#0c4a6e",
  primary: "#0ea5e9",
  "primary-foreground": "#ffffff",
  secondary: "#e0f2fe",
  "secondary-foreground": "#0369a1",
  muted: "#f1f5f9",
  "muted-foreground": "#64748b",
  accent: "#e0f2fe",
  "accent-foreground": "#0369a1",
  destructive: "#ef4444",
  "destructive-foreground": "#ffffff",
  border: "#e2e8f0",
  input: "#e2e8f0",
  ring: "#0ea5e9",
  "chart-1": "#0ea5e9",
  "chart-2": "#0284c7",
  "chart-3": "#0369a1",
  "chart-4": "#38bdf8",
  "chart-5": "#7dd3fc",
  sidebar: "#ffffff",
  "sidebar-foreground": "#0c4a6e",
  "sidebar-primary": "#0ea5e9",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#e0f2fe",
  "sidebar-accent-foreground": "#0369a1",
  "sidebar-border": "#e2e8f0",
  "sidebar-ring": "#0ea5e9",
  "font-sans": DEFAULT_FONT_SANS,
  "font-serif": DEFAULT_FONT_SERIF,
  "font-mono": DEFAULT_FONT_MONO,
  "shadow-color": "#000000",
  "shadow-opacity": "0.05",
  "shadow-blur": "20px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0px",
  "shadow-offset-y": "8px",
  "letter-spacing": "-0.01em",
  spacing: "0.25rem",
  radius: "0.625rem",
};

const oceanDark: ThemeStyles = {
  ...oceanLight,
  background: "#0c1929",
  foreground: "#e0f2fe",
  card: "#0f2d4a",
  "card-foreground": "#e0f2fe",
  popover: "#0f2d4a",
  "popover-foreground": "#e0f2fe",
  primary: "#38bdf8",
  "primary-foreground": "#0c4a6e",
  secondary: "#164e63",
  "secondary-foreground": "#e0f2fe",
  muted: "#164e63",
  "muted-foreground": "#7dd3fc",
  accent: "#164e63",
  "accent-foreground": "#38bdf8",
  destructive: "#ef4444",
  "destructive-foreground": "#ffffff",
  border: "#164e63",
  input: "#164e63",
  ring: "#38bdf8",
  "chart-1": "#38bdf8",
  "chart-2": "#7dd3fc",
  "chart-3": "#0ea5e9",
  "chart-4": "#0284c7",
  "chart-5": "#bae6fd",
  sidebar: "#0f2d4a",
  "sidebar-foreground": "#e0f2fe",
  "sidebar-primary": "#38bdf8",
  "sidebar-primary-foreground": "#0c4a6e",
  "sidebar-accent": "#164e63",
  "sidebar-accent-foreground": "#e0f2fe",
  "sidebar-border": "#164e63",
  "sidebar-ring": "#38bdf8",
  "shadow-color": "#000000",
  "shadow-opacity": "0.4",
  "shadow-blur": "25px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0px",
  "shadow-offset-y": "10px",
};

const emberLight: ThemeStyles = {
  background: "#fff7ed",
  foreground: "#7c2d12",
  card: "#ffffff",
  "card-foreground": "#7c2d12",
  popover: "#ffffff",
  "popover-foreground": "#7c2d12",
  primary: "#f97316",
  "primary-foreground": "#ffffff",
  secondary: "#ffedd5",
  "secondary-foreground": "#c2410c",
  muted: "#f1f5f9",
  "muted-foreground": "#64748b",
  accent: "#ffedd5",
  "accent-foreground": "#c2410c",
  destructive: "#ef4444",
  "destructive-foreground": "#ffffff",
  border: "#e2e8f0",
  input: "#e2e8f0",
  ring: "#f97316",
  "chart-1": "#f97316",
  "chart-2": "#ea580c",
  "chart-3": "#c2410c",
  "chart-4": "#fb923c",
  "chart-5": "#fdba74",
  sidebar: "#ffffff",
  "sidebar-foreground": "#7c2d12",
  "sidebar-primary": "#f97316",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#ffedd5",
  "sidebar-accent-foreground": "#c2410c",
  "sidebar-border": "#e2e8f0",
  "sidebar-ring": "#f97316",
  "font-sans": DEFAULT_FONT_SANS,
  "font-serif": DEFAULT_FONT_SERIF,
  "font-mono": DEFAULT_FONT_MONO,
  "shadow-color": "#000000",
  "shadow-opacity": "0.05",
  "shadow-blur": "20px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0px",
  "shadow-offset-y": "8px",
  "letter-spacing": "-0.01em",
  spacing: "0.25rem",
  radius: "0.625rem",
};

const emberDark: ThemeStyles = {
  ...emberLight,
  background: "#29180c",
  foreground: "#ffedd5",
  card: "#4a1f0f",
  "card-foreground": "#ffedd5",
  popover: "#4a1f0f",
  "popover-foreground": "#ffedd5",
  primary: "#fb923c",
  "primary-foreground": "#7c2d12",
  secondary: "#7c2d12",
  "secondary-foreground": "#ffedd5",
  muted: "#7c2d12",
  "muted-foreground": "#fdba74",
  accent: "#7c2d12",
  "accent-foreground": "#fb923c",
  destructive: "#ef4444",
  "destructive-foreground": "#ffffff",
  border: "#7c2d12",
  input: "#7c2d12",
  ring: "#fb923c",
  "chart-1": "#fb923c",
  "chart-2": "#fdba74",
  "chart-3": "#f97316",
  "chart-4": "#ea580c",
  "chart-5": "#fed7aa",
  sidebar: "#4a1f0f",
  "sidebar-foreground": "#ffedd5",
  "sidebar-primary": "#fb923c",
  "sidebar-primary-foreground": "#7c2d12",
  "sidebar-accent": "#7c2d12",
  "sidebar-accent-foreground": "#ffedd5",
  "sidebar-border": "#7c2d12",
  "sidebar-ring": "#fb923c",
  "shadow-color": "#000000",
  "shadow-opacity": "0.4",
  "shadow-blur": "25px",
  "shadow-spread": "0px",
  "shadow-offset-x": "0px",
  "shadow-offset-y": "10px",
};

export const defaultLightThemeStyles: ThemeStyles = phosphorLight;
export const defaultDarkThemeStyles: ThemeStyles = phosphorDark;

export const themes: ThemePreset[] = [
  {
    id: "phosphor",
    name: "Phosphor",
    description: "Fresh green-accented theme with a light/dark pair",
    styles: {
      light: phosphorLight,
      dark: phosphorDark,
    },
  },
  {
    id: "simple",
    name: "Simple",
    description: "Clean neutral theme with subtle blue accents",
    styles: {
      light: simpleLight,
      dark: simpleDark,
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep blue tones inspired by the sea",
    styles: {
      light: oceanLight,
      dark: oceanDark,
    },
  },
  {
    id: "ember",
    name: "Ember",
    description: "Warm orange accents for a fiery feel",
    styles: {
      light: emberLight,
      dark: emberDark,
    },
  },
];

export function getThemeById(id: string): ThemePreset | undefined {
  return themes.find((t) => t.id === id);
}

export const defaultThemeState: ThemeEditorState = {
  styles: {
    light: phosphorLight,
    dark: phosphorDark,
  },
  currentMode:
    typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light",
  hslAdjustments: {
    hueShift: 0,
    saturationScale: 1,
    lightnessScale: 1,
  },
};

function stylesToCSS(styles: ThemeStyles): string {
  return Object.entries(styles)
    .map(([key, value]) => `  --${key}: ${value};`)
    .join("\n");
}

export function buildThemeCSS(theme: ThemePreset): string {
  return `:root {\n${stylesToCSS(theme.styles.light)}\n}\n\n.dark {\n${stylesToCSS(theme.styles.dark)}\n}`;
}
